name: ratefit-env

dependencies:
    - python=3.7
    - pybind11
    - cmake
    - gfortran_linux-64  # [linux]
    - numpy
    - scipy
    - pyyaml
    - mako
    - pytest
    - pytest-cov
    - future
    - flake8
    - pylint
