# cmd: conda build .
package:
    name: RateFit
    version: "0.1.0"

source:
    path: .

requirements:
    build:
        - python
    run:
        - python
        - numpy
        - scipy
        - pandas
        - mako
        - pytest
        - pytest-cov
        - future
        - flake8
        - pylint
