# cmd: conda build . -c auto-mech -c rdkit -c openbabel -c conda-forge
package:
    name: RateFit
    version: "0.1.0"

source:
    path: .

requirements:
    build:
        - python
    run:
        - python
        - numpy
        - scipy
        - mako
        - pytest
        - pytest-cov
        - future
        - flake8
        - pylint
        - rdkit::rdkit
        - openbabel::openbabel
        - conda-forge::qcelemental
        - conda-forge::nglview
        - auto-mech::autoparse
        - auto-mech::x2z
        - auto-mech::transformations
